# Generated by Django 3.2.9 on 2021-12-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='myblog/pictures'),
        ),
    ]
